import { InternalServerErrorException, NotFoundException } from "@nestjs/common";

export const handleError = (error: Error, logger) => {
    if (error instanceof NotFoundException) {
        throw ('ya existe el sistema');
    }
    else if (error instanceof NotFoundException) {
        throw error;
    }
    else {
        logger.error(`Error: ${error.message}`);
        throw new InternalServerErrorException('Error del servicio al procesar la operaci√≥n.');
    }
}